name: update-cache

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
     - 'package-lock.json'

jobs:
  cache:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Cache node modules
      id: node-modules
      uses: actions/cache@v3
      env:
        cache-name: node-modules
      with:
        path: node_modules
        key: ${{ runner.os }}-cache-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
        restore-keys: ${{ runner.os }}-cache-${{ env.cache-name }}-
    - name: Install Dependencies
      if: steps.node-modules.outputs.cache-hit != 'true'
      run: npm ci
